import type { Exercise } from './types'

export const WORKOUT_DATABASE: Exercise[] = [
  // ================= 유산소 운동 =================
  {
    id: 'swimming',
    name: '수영 (자유형/배영)',
    category: '유산소',
    targetGoals: ['체중감량', '체력증진', '유연성'],
    environments: ['야외', '헬스장'],
    burdenParts: ['어깨'],
    effectiveness: 10,
    volume: '30~40분 지속',
    caution: '어깨 회전근개 통증이 있다면 접영이나 과도한 스트로크를 피하고 배영 위주로 진행하세요.',
    badges: ['무릎 부담 없음', '전신 유산소', '관절 보호'],
    aliases: ['수영', '자유형', '배영', '평영', '수중운동', '아쿠아로빅'],
    description: '물속 부력으로 하체 관절 충격 없이 전신 칼로리를 최대로 소모하는 유산소 운동입니다.',
  },
  {
    id: 'indoor_cycling',
    name: '실내 자전거 (사이클)',
    category: '유산소',
    targetGoals: ['체중감량', '근력강화', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['허벅지'],
    effectiveness: 9,
    volume: '25~35분 (인터벌 2분 강 / 1분 약)',
    caution: '안장 높이가 너무 낮으면 무릎에 부담이 가므로 페달이 가장 아래일 때 무릎이 10~15도 굽혀지게 맞추세요.',
    badges: ['무릎 충격 최소화', '홈트 가능', '하체 지구력'],
    aliases: ['자전거', '실내사이클', '사이클', '스핀바이크', '따릉이'],
    description: '체중 부하가 분산되어 발목과 무릎 충격을 줄이면서 높은 유산소 효율을 냅니다.',
  },
  {
    id: 'elliptical',
    name: '일립티컬 머신',
    category: '유산소',
    targetGoals: ['체중감량', '체력증진'],
    environments: ['헬스장'],
    burdenParts: [],
    effectiveness: 9,
    volume: '30분 지속 페이스',
    caution: '발뒤꿈치가 페달에서 떨어지지 않게 밀착하고 상체 핸들을 가볍게 쥐어 균형을 유지하세요.',
    badges: ['관절 충격 제로', '전신 유산소', '심폐 강화'],
    aliases: ['일립티컬', '타원형운동기구', '크로스트레이너'],
    description: '공중에서 타원을 그리는 궤적으로 발목, 무릎, 허리에 충격 없이 런닝 수준의 칼로리를 소모합니다.',
  },
  {
    id: 'rowing_machine',
    name: '로잉 머신 (실내 노젓기)',
    category: '유산소',
    targetGoals: ['체중감량', '체력증진', '근력강화'],
    environments: ['헬스장', '홈트'],
    burdenParts: ['허리', '손목'],
    effectiveness: 9,
    volume: '500m × 4세트 (세트 간 휴식 1분)',
    caution: '허리를 구부리지 말고 다리로 먼저 밀어낸 후 상체와 팔을 당기세요.',
    badges: ['전신 85% 근육 사용', '칼로리 폭탄', '등/코어 강화'],
    aliases: ['로잉', '노젓기', '콘셉트2'],
    description: '하체, 등, 코어, 팔을 모두 활용하여 짧은 시간에 높은 심폐 및 근지구력 훈련을 제공합니다.',
  },
  {
    id: 'incline_walking',
    name: '경사도 걷기 (인클라인 워킹)',
    category: '유산소',
    targetGoals: ['체중감량', '체력증진'],
    environments: ['헬스장', '야외'],
    burdenParts: ['종아리', '발목'],
    effectiveness: 8,
    volume: '경사 8~12%, 속도 4~5km/h로 30분',
    caution: '손잡이에 과도하게 매달리지 말고 엉덩이와 햄스트링에 자극을 느끼며 걸으세요.',
    badges: ['무릎 충격 적음', '체지방 연소', '둔근 자극'],
    aliases: ['경사걷기', '인클라인', '등산걷기', '천국의계단대체', '트레드밀워킹'],
    description: '뛰지 않고 걷기만으로도 심박수를 끌어올려 무릎 충격 없이 런닝 이상의 칼로리를 소모합니다.',
  },
  {
    id: 'brisk_walking',
    name: '파워 워킹 (빠르게 걷기)',
    category: '유산소',
    targetGoals: ['체중감량', '체력증진', '유연성'],
    environments: ['홈트', '야외'],
    burdenParts: [],
    effectiveness: 7,
    volume: '40~50분 (보폭을 평소보다 10cm 넓게)',
    caution: '발뒤꿈치부터 발바닥 전체, 발가락 순으로 부드럽게 지면을 롤링하듯 디디세요.',
    badges: ['부상 위험 최저', '야외/산책로', '기구 불필요'],
    aliases: ['걷기', '파워워킹', '속보', '산책'],
    description: '남녀노소 관절 부담 없이 언제 어디서나 안전하게 지방을 연소할 수 있는 기초 유산소입니다.',
  },

  // ================= 하체 근력 운동 =================
  {
    id: 'hip_thrust_bridge',
    name: '힙 브릿지 / 힙 쓰러스트',
    category: '하체근력',
    targetGoals: ['근력강화', '체중감량', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: [],
    effectiveness: 9,
    volume: '15~20회 × 4세트',
    caution: '골반을 들어 올릴 때 허리가 과신전되지 않도록 복부에 단단히 힘을 주고 둔근을 쥐어짜세요.',
    badges: ['무릎 부담 제로', '허리 통증 완화', '애플힙 완성'],
    aliases: ['힙브릿지', '브릿지', '힙쓰러스트', '엉덩이운동', '골반운동'],
    description: '무릎 관절을 거의 쓰지 않고 엉덩이와 햄스트링만을 집중 강화하는 최고의 무릎 친화적 하체 운동입니다.',
  },
  {
    id: 'lying_leg_curl',
    name: '라잉 레그 컬 (밴드/머신)',
    category: '하체근력',
    targetGoals: ['근력강화'],
    environments: ['홈트', '헬스장'],
    burdenParts: [],
    effectiveness: 8,
    volume: '15회 × 3세트',
    caution: '골반이 패드에서 뜨지 않도록 누르고, 내릴 때 햄스트링의 긴장을 유지하며 천천히 저항하세요.',
    badges: ['무릎 앞쪽 통증 없음', '허벅지 뒷라인', '단일 관절 고립'],
    aliases: ['레그컬', '라잉레그컬', '햄스트링컬', '다리접기'],
    description: '스쿼트 시 무릎 전면에 통증이 있는 분들에게 허벅지 뒤쪽(햄스트링) 근력을 안전하게 길러줍니다.',
  },
  {
    id: 'seated_calf_raise',
    name: '시티드 카프 레이즈',
    category: '하체근력',
    targetGoals: ['근력강화', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['종아리', '발목'],
    effectiveness: 7,
    volume: '20회 × 3세트',
    caution: '발뒤꿈치를 최대한 높이 들어올리고 최상단에서 1초 정지 후 천천히 내리세요.',
    badges: ['무릎/허리 부담 없음', '하체 펌핑', '발목 안정성'],
    aliases: ['카프레이즈', '종아리운동', '발뒤꿈치들기'],
    description: '앉아서 진행하여 체중이 무릎이나 척추에 실리지 않고 종아리 가자미근만을 정밀 타격합니다.',
  },
  {
    id: 'step_box_climb',
    name: '스텝박스 슬로우 스텝업',
    category: '하체근력',
    targetGoals: ['근력강화', '체중감량', '체력증진'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: ['무릎'],
    effectiveness: 8,
    volume: '좌우 각 12회 × 3세트',
    caution: '올라갈 때 앞발 뒤꿈치로 상자를 밀며 엉덩이에 체중을 실어주고 무릎이 안쪽으로 모이지 않게 주의하세요.',
    badges: ['기능성 하체', '밸런스 향상', '계단운동 대체'],
    aliases: ['스텝업', '스텝박스', '계단오르기', '박스스텝'],
    description: '착지 충격이 없어 관절에 안전하며 둔근과 대퇴사두근의 기능적 협응력을 길러줍니다.',
  },
  {
    id: 'goblet_squat',
    name: '고블렛 스쿼트',
    category: '하체근력',
    targetGoals: ['근력강화', '체중감량'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['무릎', '허벅지', '허리'],
    effectiveness: 9,
    volume: '12회 × 4세트',
    caution: '가슴 앞에 덤벨을 안아 상체 각도를 세우고, 무릎이 발가락 방향을 향하도록 벌리며 앉으세요.',
    badges: ['코어 & 하체 동시강화', '척추 부담 감소', '전신 협응'],
    aliases: ['스쿼트', '고블릿스쿼트', '맨몸스쿼트', '앉았다일어서기'],
    description: '바벨 백스쿼트 대비 허리에 가해지는 전단력이 대폭 줄어들어 안전하게 하체 전체를 자극합니다.',
  },
  {
    id: 'bulgarian_split_squat',
    name: '불가리안 스플릿 스쿼트',
    category: '하체근력',
    targetGoals: ['근력강화', '체중감량'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['무릎', '허벅지'],
    effectiveness: 9,
    volume: '좌우 각 10회 × 3세트',
    caution: '뒷다리는 의자나 벤치에 가볍게 얹어 균형만 잡고, 앞다리 둔근과 대퇴사두에 80% 체중을 실으세요.',
    badges: ['골반 좌우 불균형 개선', '고강도 하체', '둔근 집중'],
    aliases: ['불스스', '런지', '스플릿스쿼트', '한발스쿼트'],
    description: '허리 부담 없이 한쪽 다리씩 고강도로 둔근과 하체를 발달시키는 최고의 편측성 운동입니다.',
  },

  // ================= 상체 근력 운동 =================
  {
    id: 'lat_pulldown',
    name: '랫 풀다운 (머신/밴드)',
    category: '상체근력',
    targetGoals: ['근력강화', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['어깨', '팔꿈치'],
    effectiveness: 9,
    volume: '12~15회 × 4세트',
    caution: '상체를 과도하게 뒤로 눕히지 말고 쇄골 방향으로 바를 지그시 당기며 광배근을 수축하세요.',
    badges: ['턱걸이 대체', '넓은 등 라인', '허리 부담 제로'],
    aliases: ['랫풀다운', '풀다운', '등당기기', '턱걸이대체', '풀업대체'],
    description: '체중을 매달지 않고 원하는 중량으로 안전하게 광배근과 등 전체를 발달시킵니다.',
  },
  {
    id: 'seated_cable_row',
    name: '시티드 케이블 / 밴드 로우',
    category: '상체근력',
    targetGoals: ['근력강화', '유연성', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['손목', '팔꿈치'],
    effectiveness: 9,
    volume: '15회 × 3세트',
    caution: '어깨가 위로 솟지 않도록 하강 고정하고 견갑골을 모으면서 배꼽 방향으로 당기세요.',
    badges: ['라운드숄더 교정', '바른 자세', '허리 안정'],
    aliases: ['케이블로우', '시티드로우', '등운동', '밴드로우', '바벨로우대체'],
    description: '앉아서 진행하여 허리 부담을 없애고 굽은 어깨와 등을 펴주는 데 탁월합니다.',
  },
  {
    id: 'chest_press_machine',
    name: '체스트 프레스 머신',
    category: '상체근력',
    targetGoals: ['근력강화'],
    environments: ['헬스장'],
    burdenParts: ['어깨', '손목', '팔꿈치'],
    effectiveness: 9,
    volume: '12회 × 4세트',
    caution: '손잡이 높이를 가슴 중앙선에 맞추고 팔꿈치가 어깨선보다 위로 올라가지 않게 하세요.',
    badges: ['벤치프레스 대체', '가슴 고립', '안전장치 완비'],
    aliases: ['체스트프레스', '가슴머신', '벤치프레스대체', '가슴밀기'],
    description: '프리웨이트 덤벨/바벨 대비 궤도가 고정되어 손목 꺾임과 어깨 탈구 위험 없이 가슴을 자극합니다.',
  },
  {
    id: 'pec_deck_fly',
    name: '펙 덱 플라이 (버터플라이)',
    category: '상체근력',
    targetGoals: ['근력강화', '유연성'],
    environments: ['헬스장'],
    burdenParts: ['어깨', '팔꿈치'],
    effectiveness: 8,
    volume: '15회 × 3세트',
    caution: '팔꿈치를 살짝 굽힌 상태를 유지하고 어깨가 앞으로 말리지 않게 가슴을 활짝 열어주세요.',
    badges: ['가슴 안쪽 모으기', '손목 부담 없음', '스트레칭 효과'],
    aliases: ['펙덱플라이', '플라이', '버터플라이', '가슴모으기'],
    description: '손목에 덤벨을 쥘 필요 없이 팔 패드로 밀어 가슴 근육의 이완과 수축을 극대화합니다.',
  },
  {
    id: 'pushup_incline',
    name: '인클라인 푸시업 (벽/테이블)',
    category: '상체근력',
    targetGoals: ['근력강화', '체중감량', '체력증진'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: ['손목', '어깨'],
    effectiveness: 8,
    volume: '12~15회 × 3세트',
    caution: '손목이 꺾이지 않도록 지지대를 단단히 잡고 머리부터 발끝까지 일직선을 유지하세요.',
    badges: ['바닥 푸시업 대체', '손목/어깨 부담 감소', '맨몸 가슴운동'],
    aliases: ['푸시업', '팔굽혀펴기', '인클라인푸시업', '벽푸시업', '무릎푸시업'],
    description: '경사각을 높여 체중 부하를 줄임으로써 손목과 어깨 부담 없이 상체 전면을 강화합니다.',
  },
  {
    id: 'seated_dumbbell_shoulder_press',
    name: '시티드 덤벨 숄더 프레스',
    category: '상체근력',
    targetGoals: ['근력강화'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['어깨', '손목', '팔꿈치'],
    effectiveness: 8,
    volume: '12회 × 3세트',
    caution: '등받이에 등을 밀착하고 팔꿈치가 몸통 앞쪽 30도 각도를 유지하며 수직으로 올리세요.',
    badges: ['허리 부담 없음', '어깨 볼륨업', '상체 밸런스'],
    aliases: ['숄더프레스', '덤벨프레스', '밀리터리프레스대체', '어깨운동'],
    description: '등받이에 체중을 지지하여 서서 할 때 발생하는 허리 반동과 부담을 완벽히 차단합니다.',
  },

  // ================= 코어 & 밸런스 =================
  {
    id: 'deadbug',
    name: '데드버그 (Deadbug)',
    category: '코어',
    targetGoals: ['근력강화', '유연성', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: [],
    effectiveness: 9,
    volume: '좌우 왕복 12회 × 3세트',
    caution: '동작 중 허리가 바닥에서 뜨지 않도록 복압을 유지하고 반대쪽 팔다리를 천천히 교차해서 뻗으세요.',
    badges: ['플랭크 대체', '허리/목 통증 제로', '재활 코어 1순위'],
    aliases: ['데드버그', '플랭크대체', '윗몸일으키기대체', '복근운동', '코어운동'],
    description: '목이나 허리를 꺾지 않고 바닥에 누워 안전하게 심부 코어 근육(복횡근)을 단련합니다.',
  },
  {
    id: 'bird_dog',
    name: '버드독 (Bird-Dog)',
    category: '코어',
    targetGoals: ['근력강화', '유연성', '체력증진'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: ['손목', '무릎'],
    effectiveness: 9,
    volume: '좌우 각 10회 (3초 유지) × 3세트',
    caution: '팔다리를 너무 높이 들어 허리가 꺾이지 않게 몸통과 평행을 이루는 높이까지만 뻗으세요.',
    badges: ['허리디스크 안심', '척추 기립근 강화', '코어 밸런스'],
    aliases: ['버드독', '네발기기', '허리코어', '척추안정화'],
    description: '척추 전문의들이 가장 추천하는 저부하 고효율 척추 안정화 코어 강화 운동입니다.',
  },
  {
    id: 'hollow_body_hold',
    name: '할로우 바디 홀드 (무릎 굽혀 변형)',
    category: '코어',
    targetGoals: ['근력강화', '체중감량'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['복부'],
    effectiveness: 8,
    volume: '20~30초 유지 × 3세트',
    caution: '허리(요추)를 바닥에 완벽히 밀착시키고 배꼽을 바닥 쪽으로 쥐어짜듯 긴장하세요.',
    badges: ['목 부담 없음', '체조식 코어', '뱃살 탄력'],
    aliases: ['할로우바디', '할로우', '코어버티기'],
    description: '크런치나 싯업처럼 목을 당기지 않고도 복직근과 코어 전체를 강력하게 자극합니다.',
  },
  {
    id: 'side_plank_knees',
    name: '닐링 사이드 플랭크 (무릎 대고)',
    category: '코어',
    targetGoals: ['근력강화', '유연성'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['어깨', '팔꿈치'],
    effectiveness: 8,
    volume: '좌우 각 20~30초 × 3세트',
    caution: '팔꿈치가 어깨 바로 아래 오도록 배치하고 골반이 아래로 처지지 않게 들어 올리세요.',
    badges: ['옆구리 탄력', '중둔근 강화', '손목 부담 없음'],
    aliases: ['사이드플랭크', '옆구리플랭크', '무릎사이드플랭크'],
    description: '무릎을 바닥에 대어 부하를 줄이면서 외복사근과 골반 안정화 근육을 안전하게 단련합니다.',
  },

  // ================= 유연성 & 스트레칭 =================
  {
    id: 'cat_camel_stretch',
    name: '캣-카멜 스트레칭 (고양이 자세)',
    category: '스트레칭',
    targetGoals: ['유연성', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['손목', '무릎'],
    effectiveness: 9,
    volume: '10회 왕복 (호흡에 맞춰 천천히)',
    caution: '숨을 들이마시며 등을 오목하게 낮추고, 내쉬며 등을 둥글게 천장 쪽으로 밀어 올리세요.',
    badges: ['척추 유연성', '허리 뻐근함 해소', '워밍업/쿨다운'],
    aliases: ['고양이자세', '캣카멜', '척추스트레칭', '등스트레칭'],
    description: '척추 분절 하나하나를 부드럽게 움직여 굳은 등과 허리의 긴장을 즉시 풀어줍니다.',
  },
  {
    id: 'seated_hamstring_stretch',
    name: '의자 시티드 햄스트링 스트레칭',
    category: '스트레칭',
    targetGoals: ['유연성'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: [],
    effectiveness: 8,
    volume: '좌우 각 30초 유지 × 3세트',
    caution: '허리를 둥글게 말지 말고 가슴을 편 상태에서 고관절을 접어 상체를 앞으로 숙이세요.',
    badges: ['허리 부담 없음', '의자에서 가능', '하체 혈액순환'],
    aliases: ['햄스트링스트레칭', '다리스트레칭', '다리찢기대체'],
    description: '바닥에 앉기 힘든 분들도 의자에 걸터앉아 허리 부담 없이 햄스트링을 깊게 이완합니다.',
  },
  {
    id: 'doorway_chest_stretch',
    name: '도어웨이 가슴 & 전면 어깨 스트레칭',
    category: '스트레칭',
    targetGoals: ['유연성'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: [],
    effectiveness: 9,
    volume: '20초 유지 × 3세트',
    caution: '문틀에 팔꿈치를 대고 한 발 앞으로 나가며 가슴 앞쪽이 기분 좋게 늘어나는 지점에서 멈추세요.',
    badges: ['굽은 등 펴기', '어깨 충돌 예방', '도구 불필요'],
    aliases: ['가슴스트레칭', '어깨스트레칭', '문틀스트레칭', '라운드숄더스트레칭'],
    description: '문틀이나 벽 모서리만 있으면 누구나 굳어있는 소흉근과 어깨 전면을 안전하게 열어줍니다.',
  },
  {
    id: 'figure_four_piriformis_stretch',
    name: '누워서 하는 4자 둔근/이상근 스트레칭',
    category: '스트레칭',
    targetGoals: ['유연성', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: [],
    effectiveness: 9,
    volume: '좌우 각 30초 유지 × 2세트',
    caution: '한쪽 발목을 반대쪽 허벅지에 얹고, 아래쪽 다리를 양손으로 잡고 가슴 쪽으로 지그시 당기세요.',
    badges: ['좌골신경통 완화', '골반 교정', '무릎 부담 없음'],
    aliases: ['이상근스트레칭', '4자스트레칭', '엉덩이스트레칭', '골반스트레칭'],
    description: '골반 깊숙한 이상근을 늘려 허리 뻐근함과 다리 저림을 완화하는 핵심 스트레칭입니다.',
  },

  // ================= 전신 / 컨디셔닝 =================
  {
    id: 'kettlebell_deadlift',
    name: '케틀벨 루마니안 데드리프트',
    category: '전신',
    targetGoals: ['근력강화', '체중감량', '체력증진'],
    environments: ['홈트', '헬스장'],
    burdenParts: ['허리', '손목'],
    effectiveness: 9,
    volume: '12회 × 3세트',
    caution: '무릎은 살짝만 굽힌 채 고관절을 뒤로 빼는 힙힌지(Hip Hinge) 동작에 집중하세요.',
    badges: ['전신 후면 사슬', '무릎 부담 최소', '신진대사 촉진'],
    aliases: ['데드리프트', '케틀벨데드리프트', '루마니안', '등하체동시'],
    description: '스쿼트보다 무릎 굽힘이 적어 무릎 부담을 덜면서 후면 사슬 전체를 강력하게 단련합니다.',
  },
  {
    id: 'seated_battle_rope',
    name: '시티드 배틀로프 (의자 착석)',
    category: '전신',
    targetGoals: ['체중감량', '체력증진'],
    environments: ['헬스장'],
    burdenParts: ['어깨', '팔꿈치', '손목'],
    effectiveness: 9,
    volume: '20초 전력 파도타기 / 40초 휴식 × 5라운드',
    caution: '허리를 바로 세우고 팔 전체를 이용해 리드미컬하게 파도를 만드세요.',
    badges: ['하체/무릎 부하 제로', '초고강도 유산소', '심폐 폭발'],
    aliases: ['배틀로프', '로프운동', '줄털기', 'HIIT'],
    description: '의자에 앉아서 팔과 코어로만 로프를 털어 하체 부상자도 심박수를 160 이상 끌어올릴 수 있습니다.',
  },
  {
    id: 'standing_shadow_boxing',
    name: '스탠딩 섀도 복싱 (노 점핑)',
    category: '전신',
    targetGoals: ['체중감량', '체력증진'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: ['어깨'],
    effectiveness: 8,
    volume: '3분 1라운드 × 3라운드',
    caution: '발을 구르거나 점프하지 않고 제자리에서 체중 이동과 잽/스트레이트 동작에 집중하세요.',
    badges: ['층간소음 제로', '스트레스 해소', '상체 유산소'],
    aliases: ['복싱', '섀도복싱', '권투', '유산소복싱'],
    description: '점핑 동작 없이 상체 펀치와 코어 회전만으로 층간소음과 관절 부담 없이 땀을 낼 수 있습니다.',
  },
  {
    id: 'standing_resistance_band_pull_apart',
    name: '밴드 풀 어파트 (후면 삼각근 & 등)',
    category: '상체근력',
    targetGoals: ['근력강화', '유연성'],
    environments: ['홈트', '헬스장', '야외'],
    burdenParts: ['어깨'],
    effectiveness: 8,
    volume: '15~20회 × 3세트',
    caution: '팔을 앞으로 뻗은 상태에서 양옆으로 밴드를 늘리며 날개뼈 안쪽을 꽉 조이세요.',
    badges: ['거북목 교정', '간편한 밴드 운동', '관절 보호'],
    aliases: ['밴드풀어파트', '등펴기', '어깨후면'],
    description: '가벼운 탄성 밴드로 관절 무리 없이 상체 후면 자세유지근을 강화합니다.',
  },
]
